import type { WorkCard } from "./types";

const workData: WorkCard[] = [
  {
    slug: "cb-animation-challenge",
    title: "CB Animation Challenge",
    type: "Creative Development",
    thumbSrc: "/assets/thumbs/animation.png",
    imgSrc: "/assets/projects/cb-animation-challenge.png",
    summary: "A campaign experience for a Candy Banner animation contest. Users spin an interactive slot machine to discover entries by category, then explore work submitted by developers showcasing inventive animation techniques.",
    tools: ["Vue 3", "GSAP", "Bootstrap", "Pinia", "Axios", "Express", "MongoDB"],
    link: "",
  },
  {
    slug: "batiste",
    title: "Batiste",
    type: "Creative Development",
    thumbSrc: "/assets/thumbs/batiste.png",
    imgSrc: "/assets/projects/batiste.png",
    summary: "An interactive Batiste product experience that guides users through a hair-type quiz and recommends a matching product, creating a direct path from discovery to the product page.",
    tools: ["Nuxt 2", "GSAP", "Bootstrap", "Vuex", "Axios"],
    link: "https://www.mybatiste.ca/",
  },  
  {
    slug: "candy-digital",
    title: "Candy Digital",
    type: "Creative Web Development",
    thumbSrc: "/assets/thumbs/candy-digital.png",
    imgSrc: "/assets/projects/candy-digital.png",
    summary: "A company website revamp created during the transition from Candy Banners to Candy Digital. The experience presents the studio's work and services through a polished, motion-led interface.",
    tools: ["Nuxt 3", "GSAP", "Bootstrap", "Matter.js", "Pinia", "Headless CMS", "Wordpress"],
    link: "https://candydigital.co/",
  },
  {
    slug: "cashmere",
    title: "Cashmere",
    type: "Creative Web Development",
    thumbSrc: "/assets/thumbs/cashmere.png",
    imgSrc: "/assets/projects/cashmere.png",
    summary: "A nationwide Cashmere dress competition experience that gives the audience a way to browse and vote for standout entries while celebrating creative talent across the country.",
    tools: ["Vue 3", "GSAP", "Vuex", "Bootstrap", "Axios", "Express", "MongoDB"],
    link: "",
  },
  {
    slug: "enthuse",
    title: "Enthuse",
    type: "Creative Development",
    thumbSrc: "/assets/thumbs/enthuse.png",
    imgSrc: "/assets/projects/enthuse.png",
    summary: "A festive Enthuse microsite designed to engage visitors through seasonal interactions, product discovery and downloadable discount coupons for the holiday campaign.",
    tools: ["Vue 3", "GSAP", "Bootstrap"],
    link: "",
  },
  {
    slug: "candy-digital-holiday",
    title: "Candy Digital Holiday",
    type: "Creative Development",
    thumbSrc: "/assets/thumbs/holiday.png",
    imgSrc: "/assets/projects/holiday.png",
    summary: "A holiday microsite for Candy Digital where users create personalized GIFs, download their finished creations and share them with friends and family.",
    tools: ["Vue 3", "GSAP", "Bootstrap"],
    link: "",
  },
  {
    slug: "klick-bayer",
    title: "Klick Bayer",
    type: "Web Development",
    thumbSrc: "/assets/thumbs/klick-bayer.png",
    imgSrc: "/assets/projects/klick-bayer.png",
    summary: "A focused pitch-site concept for Klick Bayer, translating the campaign direction into a concise digital presentation with a clear visual narrative.",
    tools: ["Wordpress"],
    link: "",
  },
  {
    slug: "lallemand-biofuels",
    title: "Lallemand Biofuels",
    type: "Rich Media & Banner Development",
    thumbSrc: "/assets/thumbs/lallemand-biofuels.png",
    imgSrc: "/assets/projects/lallemand-biofuels.png",
    summary: "A rich-media advertising experience for Lallemand Biofuels, built to communicate brand information clearly and attract attention on a large-format display.",
    tools: ["Javascript", "GSAP"],
    link: "",
  },
  {
    slug: "moreys",
    title: "Moreys",
    type: "Web Development",
    thumbSrc: "/assets/thumbs/moreys.png",
    imgSrc: "/assets/projects/moreys.png",
    summary: "A custom Moreys food experience combining seafood products, recipes, coupons and store discovery in one WordPress site built with reusable Gutenberg blocks.",
    tools: ["Wordpress", "React"],
    link: "",
  },
  {
    slug: "cb-spring-challenge",
    title: "CB Spring Challenge",
    type: "Creative Web Development",
    thumbSrc: "/assets/thumbs/spring.png",
    imgSrc: "/assets/projects/spring.png",
    summary: "A spring-break animation contest experience hosted by Candy Banner, giving developers a platform to submit creative work and visitors a way to discover and celebrate the entries.",
    tools: ["Nuxt 3", "Bootstrap", "GSAP"],
    link: "",
  },
  {
    slug: "infinite-verse",
    title: "Flyrank AI-Internship",
    type: "AI-Augmented Web Development",
    thumbSrc: "/assets/thumbs/infinite-verse.png",
    imgSrc: "/assets/projects/infinite-verse.png",
    summary: "This is a Bible Web App that provides users with an immersive and interactive way to explore biblical verses and related content. An AI-augmented web experience for Infinite Verse, leveraging advanced algorithms to enhance user interaction and content personalization.",
    tools: ["Next.js", "Tailwind CSS", "GSAP", "AI tools", "Firebase", "Rest APIs"],
    link: "https://infinite-verse.vercel.app/",
  },
];

export default workData;
